// native_logic_cyd suite — the compiled-in STOCK profile table (design.md §7/§23), checked from the
// CYD's side of the contract.
//
// test_control already proves every entry DECODES. This suite asks the question that actually
// matters to an operator: can the profile be RUN? A stock profile that lists fine but fails
// compileRecipe() is worse than a missing one — it looks like a factory reference right up until
// Setup refuses it, and the §23 read-only rule means the operator cannot edit their way out.
//
// So each cure entry is taken the whole way the run path takes it: decode -> phasesFromWire ->
// compileRecipe against the factory caps and the shipped calibration. Anything the controller's
// RecipeValidator would NAK, compileRecipe hard-rejects here first (that mirroring is its stated
// job), so this is the cheap host-side proxy for "this profile uploads cleanly".
//
// The table itself is GENERATED by tools/gen_profiles.cpp — never hand-edited — so a failure here
// means the authored definitions in that file are wrong, not the header.
#include <unity.h>

#include <cstring>

#include <pb_decode.h>

#include "IProfileStorage.h" // kProfileNameCap — a profile name is also the store's filesystem key
#include "oven.pb.h"
#include "oven_cal.h"
#include "phase.h"
#include "phase_codec.h"
#include "profile_facts.h" // kDefaultAmbientC — the same origin the editor/preview compile from
#include "recipe_compiler.h"
#include "settings_defaults.h"
#include "stock_profiles.h"

void setUp(void) {}
void tearDown(void) {}

namespace {

// nanopb directly rather than protocol::decode: this lane deliberately has no schema_hash
// pre-script (see platformio.ini), so pulling in lib/protocol's codec.h would drag handshake.cpp
// and its generated schema_hash.h along with it. The decode is two lines; the dependency is not.
bool decodeProfile(const uint8_t *buf, size_t len, oven_Profile &out) {
  out = oven_Profile_init_zero;
  pb_istream_t s = pb_istream_from_buffer(buf, len);
  return pb_decode(&s, oven_Profile_fields, &out);
}

// The FACTORY caps, deliberately — not the hard-max. A stock profile has to be runnable on a board
// that has never had its settings touched, which is exactly the default cap.
Caps cureCaps() {
  return Caps{0.0F, static_cast<float>(settings_defaults::UV_CAP_DEFAULT)};
}

size_t cureEntries() {
  size_t n = 0;
  for (size_t i = 0; i < control::stock::kCount; ++i) {
    if (control::stock::kEntries[i].mode == oven_Mode_MODE_CURE) {
      ++n;
    }
  }
  return n;
}

CompileResult compileEntry(const control::stock::Entry &e, oven_Profile &p) {
  p = oven_Profile_init_zero;
  TEST_ASSERT_TRUE_MESSAGE(decodeProfile(e.body, e.len, p), e.name);
  Phase phases[kMaxPhases];
  const size_t n = phase_codec::phasesFromWire(p, phases, kMaxPhases);
  TEST_ASSERT_TRUE_MESSAGE(n > 0, e.name);
  return compileRecipe(phases, n, phase_codec::modeFromWire(p.mode), oven_cal::kDefaultModel,
                       cureCaps(), profile_facts::kDefaultAmbientC, /*id=*/0, /*seq=*/0);
}

} // namespace

// The set is not empty — a table that silently lost its cure half would otherwise pass every
// other assertion here vacuously.
void test_cure_stock_set_is_present(void) {
  TEST_ASSERT_TRUE(cureEntries() > 0);
}

// Every stock cure profile compiles into an uploadable recipe on factory settings.
void test_every_cure_stock_profile_compiles(void) {
  for (size_t i = 0; i < control::stock::kCount; ++i) {
    const control::stock::Entry &e = control::stock::kEntries[i];
    if (e.mode != oven_Mode_MODE_CURE) {
      continue;
    }
    oven_Profile p = oven_Profile_init_zero;
    const CompileResult r = compileEntry(e, p);
    TEST_ASSERT_TRUE_MESSAGE(r.hardValid, e.name);
    TEST_ASSERT_EQUAL_INT_MESSAGE(static_cast<int>(CompileReject::None), static_cast<int>(r.reject),
                                  e.name);
    TEST_ASSERT_TRUE_MESSAGE(r.recipe.segments_count > 0, e.name);
  }
}

// Every cure phase sits at or under the FACTORY UV cap, with the margin the cap was raised to give.
// Flame Retardant post-cures at 100 °C (Form Cure V2); against the old 100 °C default that compiled
// with exactly zero headroom, since recipe_compiler rejects on `targetC > capC`. This is what makes
// lowering UV_CAP_DEFAULT back to 100 fail loudly instead of silently breaking a factory profile.
void test_cure_stock_targets_fit_under_the_factory_cap(void) {
  const float cap = static_cast<float>(settings_defaults::UV_CAP_DEFAULT);
  float hottest = 0.0F;
  for (size_t i = 0; i < control::stock::kCount; ++i) {
    const control::stock::Entry &e = control::stock::kEntries[i];
    if (e.mode != oven_Mode_MODE_CURE) {
      continue;
    }
    oven_Profile p = oven_Profile_init_zero;
    TEST_ASSERT_TRUE(decodeProfile(e.body, e.len, p));
    for (pb_size_t k = 0; k < p.phases_count; ++k) {
      TEST_ASSERT_TRUE_MESSAGE(p.phases[k].target_c <= cap, e.name);
      if (p.phases[k].target_c > hottest) {
        hottest = p.phases[k].target_c;
      }
    }
  }
  TEST_ASSERT_TRUE_MESSAGE(hottest <= cap - 5.0F,
                           "the hottest stock cure profile has no cap headroom");
}

// A cure profile must actually cure: UV and the turntable on, and a dose authored rather than raw
// seconds. Without the turntable recipe_compiler falls back to hold_s and the dose model is
// bypassed entirely (holdFallback), which would quietly make every stock time wrong once
// beamCoverage is calibrated — the exact failure authoring dose is meant to prevent.
void test_cure_stock_profiles_author_a_dose(void) {
  for (size_t i = 0; i < control::stock::kCount; ++i) {
    const control::stock::Entry &e = control::stock::kEntries[i];
    if (e.mode != oven_Mode_MODE_CURE) {
      continue;
    }
    oven_Profile p = oven_Profile_init_zero;
    TEST_ASSERT_TRUE(decodeProfile(e.body, e.len, p));
    bool sawDose = false;
    for (pb_size_t k = 0; k < p.phases_count; ++k) {
      if (!p.phases[k].uv) {
        continue;
      }
      TEST_ASSERT_TRUE_MESSAGE(p.phases[k].motor, e.name); // UV without rotation cures one side
      TEST_ASSERT_TRUE_MESSAGE(p.phases[k].exposure_per_surface > 0.0F, e.name);
      sawDose = true;
    }
    TEST_ASSERT_TRUE_MESSAGE(sawDose, e.name);
  }
}

// No stock profile compiles with a rate-limited ramp. The generator derives each warm-up from the
// plant model with margin precisely so the factory set is amber-free out of the box; an authored
// ramp the oven cannot achieve would put every operator's first look at the library in a warning
// state and teach them to ignore it.
void test_cure_stock_ramps_are_achievable(void) {
  for (size_t i = 0; i < control::stock::kCount; ++i) {
    const control::stock::Entry &e = control::stock::kEntries[i];
    if (e.mode != oven_Mode_MODE_CURE) {
      continue;
    }
    oven_Profile p = oven_Profile_init_zero;
    const CompileResult r = compileEntry(e, p);
    for (size_t k = 0; k < r.phaseCount; ++k) {
      TEST_ASSERT_FALSE_MESSAGE(r.phases[k].rampRateLimited, e.name);
      TEST_ASSERT_FALSE_MESSAGE(r.phases[k].holdFallback, e.name);
    }
  }
}

// A profile name is the store's filesystem key (ProfileStore::validName) AND a list-row label. Path
// separators are rejected outright — the generator caught exactly that on a "Grey/Black/White" name
// — and an over-long name ellipsizes on the 320 px portrait panel, hiding what distinguishes it.
void test_cure_stock_names_are_storable_and_legible(void) {
  constexpr size_t kRowBudget = 21; // chars that fit a row label beside its "peak · ~mm:ss" facts
  for (size_t i = 0; i < control::stock::kCount; ++i) {
    const control::stock::Entry &e = control::stock::kEntries[i];
    if (e.mode != oven_Mode_MODE_CURE) {
      continue;
    }
    const size_t len = std::strlen(e.name);
    TEST_ASSERT_TRUE_MESSAGE(len > 0 && len < kProfileNameCap, e.name);
    TEST_ASSERT_TRUE_MESSAGE(len <= kRowBudget, e.name);
    TEST_ASSERT_NULL_MESSAGE(std::strchr(e.name, '/'), e.name);
    TEST_ASSERT_NULL_MESSAGE(std::strchr(e.name, '\\'), e.name);
    for (const char *c = e.name; *c != '\0'; ++c) {
      // The UI font carries 0x20-0x7F plus '°' only (fonts/README.md); anything else renders as a
      // blank box in the row the operator picks from.
      TEST_ASSERT_TRUE_MESSAGE(
          static_cast<unsigned char>(*c) >= 0x20 && static_cast<unsigned char>(*c) < 0x7F, e.name);
    }
  }
}

// Names must be unique: the name IS the store key, so two entries sharing one would have the second
// silently overwrite the first at seed time and the library would come up short with no error.
void test_cure_stock_names_are_unique(void) {
  for (size_t i = 0; i < control::stock::kCount; ++i) {
    for (size_t j = i + 1; j < control::stock::kCount; ++j) {
      TEST_ASSERT_FALSE_MESSAGE(
          std::strcmp(control::stock::kEntries[i].name, control::stock::kEntries[j].name) == 0,
          control::stock::kEntries[i].name);
    }
  }
}

int main(int, char **) {
  UNITY_BEGIN();
  RUN_TEST(test_cure_stock_set_is_present);
  RUN_TEST(test_every_cure_stock_profile_compiles);
  RUN_TEST(test_cure_stock_targets_fit_under_the_factory_cap);
  RUN_TEST(test_cure_stock_profiles_author_a_dose);
  RUN_TEST(test_cure_stock_ramps_are_achievable);
  RUN_TEST(test_cure_stock_names_are_storable_and_legible);
  RUN_TEST(test_cure_stock_names_are_unique);
  return UNITY_END();
}
