"""PlatformIO pre-script: bake the shared .proto's schema hash into the build.

Compiles proto/oven.proto to a FileDescriptorSet with the mise-pinned protoc
(see mise.toml), SHA-256s it, and writes the first 8 bytes as a uint64 constant
to $BUILD_DIR/schema/schema_hash.h. Both firmwares exchange the value in
Hello.schema_hash at boot and refuse to run on a mismatch (design.md §9).

Descriptor bytes exclude comments/whitespace (no --include_source_info), so only
real schema changes — fields, types, numbers — change the hash. The bytes are
stable for a fixed protoc release; protoc is pinned in mise.toml.
"""

import hashlib
import shutil
import subprocess
from pathlib import Path

Import("env")  # noqa: F821 — provided by the PlatformIO/SCons runtime

PROJECT_DIR = Path(env.subst("$PROJECT_DIR"))  # noqa: F821
SCHEMA_DIR = Path(env.subst("$BUILD_DIR")) / "schema"  # noqa: F821
PROTO = PROJECT_DIR / "proto" / "oven.proto"
DESC = SCHEMA_DIR / "oven.desc"
HEADER = SCHEMA_DIR / "schema_hash.h"


def _protoc():
    """Resolve protoc: activated-mise PATH first, then `mise which` for bare shells."""
    found = shutil.which("protoc")
    if found:
        return found
    mise = shutil.which("mise")
    if mise:
        probe = subprocess.run(
            [mise, "which", "protoc"], capture_output=True, text=True, cwd=PROJECT_DIR
        )
        if probe.returncode == 0 and probe.stdout.strip():
            return probe.stdout.strip()
    raise SystemExit(
        "schema_hash: protoc not found — run `mise install` (protoc is pinned in mise.toml)"
    )


SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
result = subprocess.run(
    [
        _protoc(),
        "--proto_path=proto",
        f"--descriptor_set_out={DESC}",
        "proto/oven.proto",
    ],
    cwd=PROJECT_DIR,
    capture_output=True,
    text=True,
)
if result.returncode != 0:
    raise SystemExit(f"schema_hash: protoc failed on {PROTO}:\n{result.stderr}")

digest = hashlib.sha256(DESC.read_bytes()).digest()
hash64 = int.from_bytes(digest[:8], "big")

content = (
    "// Generated by tools/schema_hash_extra_script.py — do not edit, not committed.\n"
    "// SHA-256 (first 8 bytes) of proto/oven.proto's compiled FileDescriptorSet.\n"
    "#pragma once\n"
    "#include <stdint.h>\n"
    f"#define OVEN_SCHEMA_HASH UINT64_C(0x{hash64:016x})\n"
)

# Write only on change so an untouched schema never dirties the build graph.
if not HEADER.exists() or HEADER.read_text() != content:
    HEADER.write_text(content)

env.Append(CPPPATH=[str(SCHEMA_DIR)])  # noqa: F821
