// GENERATED by tools/gen_profiles.cpp -- do not edit.
//
// The stock profile set (design.md §7/§23), compiled into the controller firmware as
// nanopb-encoded oven_Profile bodies. Regenerate with:
//   pio run -e gen_profiles && .pio/build/gen_profiles/program data/profiles
//
// Why this exists at all, rather than `uploadfs` alone: `data/profiles/**` reaches the board only
// via a SEPARATE `pio run -t uploadfs`, and the controller mounts LittleFS with
// formatOnFail=true. So a plain `-t upload` leaves the §23 empty state, and a corrupt filesystem
// silently reformats the library away -- stock included -- with no recovery short of a USB
// reflash. §23 promises the factory references "can't be lost"; that promise needs a copy the
// filesystem cannot take with it. Boot seeds any missing entry from here, which also makes
// `uploadfs` optional rather than load-bearing.
//
// This is the ONLY legitimate input to ProfileStore::seedStock() -- see the warning there. It is
// reviewed source compiled into this firmware, never anything that arrived over the wire.
//
// const, so it lives in flash .rodata and costs the controller's DRAM nothing (§6a).
#pragma once

#include <cstddef>
#include <cstdint>

#include "oven.pb.h"

namespace control {
namespace stock {

struct Entry {
  const char *name;
  oven_Mode mode;
  const uint8_t *body; // nanopb-encoded oven_Profile
  size_t len;
};

inline constexpr uint8_t kSAC305[] = {
    0x08, 0x02, 0x12, 0x06, 0x53, 0x41, 0x43, 0x33, 0x30, 0x35, 0x18, 0x01,
    0x22, 0x15, 0x0A, 0x04, 0x53, 0x6F, 0x61, 0x6B, 0x15, 0x00, 0x00, 0x25,
    0x43, 0x1D, 0x00, 0x00, 0xC8, 0x42, 0x25, 0x00, 0x00, 0xB4, 0x42, 0x22,
    0x17, 0x0A, 0x06, 0x52, 0x65, 0x66, 0x6C, 0x6F, 0x77, 0x15, 0x00, 0x00,
    0x79, 0x43, 0x1D, 0x00, 0x00, 0x20, 0x42, 0x25, 0x00, 0x00, 0xF0, 0x41,
    0x22, 0x0B, 0x0A, 0x04, 0x43, 0x6F, 0x6F, 0x6C, 0x15, 0x00, 0x00, 0x48,
    0x42,
};

inline constexpr Entry kEntries[] = {
    {"SAC305", oven_Mode_MODE_REFLOW, kSAC305, sizeof(kSAC305)},
};

inline constexpr size_t kCount = sizeof(kEntries) / sizeof(kEntries[0]);

} // namespace stock
} // namespace control
